services:
  logseq:
    build: .  # Builds your Dockerfile
    # OR image: ghcr.io/logseq/logseq-webapp:latest  # If skipping custom
    restart: unless-stopped
    volumes:
      - graphs:/data
    labels:
      - "traefik.enable=true"
volumes:
  graphs:
